### ISSUE TITLE
nblas dependency error

### ISSUE THREAD

**Issue by williamngan** [mateogianolio/vectorious#111]
Hi, I'm trying out vectorious for a project. Getting this error during `npm install`. 

```
ERROR in ./~/nblas/addon.js
Module not found: Error: Can't resolve './build/Release/addon' in '{...}/node_modules/nblas'
 @ ./~/nblas/addon.js 4:14-46
 @ ./~/vectorious/vectorious.js
 @ ./src/app.ts
```

Any idea on how to resolve it? Or is it possible to install vectorious without nblas?

Thanks!

**Comment by mateogianolio** [comment]
Weird, will check it out this weekend.

You can try including it without blas (if you don't want it): ’require('vectorious/withoutblas')’

**Comment by mateogianolio** [comment]
I don't know why you get that particular error though, could you tell me which OS you are running and if you have any BLAS library installed?

Just tried it on Ubuntu 16.04 with and without libblas-dev installed and it seems to work fine, both with node v4.2.6 and latest (v8.1.1).

**Comment by williamngan** [comment]
Yes, I'm using a new Macbook (Sierra 10.12.5) with XCode installed. 

Do I need to install BLAS first?

**Comment by williamngan** [comment]
I think this is probably a webpack problem. I tried it again using a webpack es6 boilerplate and the error still occurs. Here's a screenshot for your reference:

![image](https://user-images.githubusercontent.com/4358746/27224024-c2d73990-522e-11e7-8e87-c70a342a1068.png)

(Apologies that I mistyped the error as "npm install" in the beginning!)

**Comment by mateogianolio** [comment]
Try `import {Vector} from 'vectorious/withoutblas'`.

**Comment by mateogianolio** [comment]
This is not the intended behaviour though, it should gracefully fallback to using without blas so I'll keep this issue open.

**Comment by marlinilram** [comment]
Met same problem when I tried npm run start

**Comment by Khalid-Nowaf** [comment]
is there any way to use BLAS in the browser?

**Comment by alizbazar** [comment]
Also, an exception occurs if running on `react-native`. `withoutblas` works fine, though.

**Comment by metabench** [comment]
A while ago I went off using and working on Vectorious because of its dependency on blas, and the requirement to have blas installed already. I'm still interested in the project though, whether working on it directly, or working on a rival of some sort.

@mateogianolio Is your opinion on how blas gets linked the same as I recall from a few years ago - ie require it to be installed on the system? I also don't know if there would be any licensing complications by linking that way.

I would definitely prefer if blas were to be compiled on the system during the install process, probably using napi to have blas running as a node addon. Still, there is other work that I plan on doing in the shorter term involving compiled C++ vector maths. One approach that would fit in with the Vectorious project would be for me to port non-blas JS code to C++ to run through a node addon, and potentially be compiled to WASM and be run in either node or the browser.

I'm also interested in trying some other languages. Rust looks the most promising for WASM compilation right now.

**Comment by mateogianolio** [comment]
My view is not as strict regarding compilation during the install process as it was before. I would actually be open to do an experiment to see if it is viable. It is still kind of a pain to convert between js and c types, how do you propose to solve that?

I had some preconceived notions on performance in the past, which in hindsight might have been detrimental to the success of this project. I think a set of well crafted benchmarks would help solve that issue, so that future performance discussions can be based on empirical evidence rather than opinions.

Rust WASM compilation sounds incredibly interesting. Have you tried it?

**Comment by metabench** [comment]
"I also don't know if there would be any licensing complications by linking that way." - I was referring to linking through compiling the code, so the blas code became part of the Vectorious codebase, much like V8 is part of the node.js codebase.

When I worked on C and JS code before, my focus was on carrying out operations on existing typed arrays. It was impossible until I knew how, then the few lines of boilerplate code needed became easy to use. Now there is the N-API system which is an interface between the V8 world and node.js. That's what I propose starting with, but if there are shorter code routes that do better in benchmarks then I'm interested in them too.

I've not done anything that difficult regarding Rust compilation. Maybe I've run a minimal Rust example, but I've not done anything that serious with WASM. Soon would be a good time to start. Higher priority to me in the short term is C and C++ code compiled and running as a node addon. Then I'm interested in compiling that same code to WASM. Also interested in writing optimized JS code in a way where JS functions can be recompiled / transpiled to C / C++ / other languages.

**Comment by mateogianolio** [comment]
Discussion is kind of off-topic for this issue. Installing vectorious without BLAS is now described in the README (`npm install vectorious --no-optional`).
