### ISSUE TITLE
Change data structure to ndarray

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#124]
* https://github.com/scijs/ndarray

Instead of having two classes (`Matrix`, `Vector`) that both implements the same data structure, we should consider the possibility of extending the `ndarray` data structure instead. This would

* allow us to implement tensors (#116)
* keep the code DRY
* make vectorious compatible with scijs
* make vectorious more similar to numpy

**Comment by metabench** [comment]
I'm glad I had a look into https://github.com/scijs/ndarray/blob/master/ndarray.js before starting to write my own tensor js code. The code is an interesting read - I was surprised to see it compiles some of its own js and calls `var procedure = new Function("CTOR_LIST", "ORDER", code.join("\n"))` on [line 251](https://github.com/scijs/ndarray/blob/master/ndarray.js#L251). I'm not saying there is anything wrong with coding like that - it's been made by a skilled programmer who must have had a reason to do it. Just right now, I can't figure out what that reason is, and don't want to make assumptions about one style of code being faster than others without seeing benchmarks.

I'm still thinking of writing my own tensor js library. It would require Typed Arrays, and not have any workaround for when they don't exist. 

My aim would be to have it run as quickly as possible in JS. I'm also interested in what can be done to port such code (which in many cases will be a lot like C++ anyway) to node addons and WASM compilation. I don't expect results all that soon, but if there are ways that NDArray could be more suitable for vectorious than it currently is, I could pay that attention when developing my own tensor library. At its heart will be a relatively simple indexing function, used for both get and set.

One type of coding style that's worth considering is JS that's possible to recompile / transpile to C++. If you think of writing some parts / algorithms in a JS style that's got almost identical syntax to C++, using [Hungarian Notation ](https://en.wikipedia.org/wiki/Hungarian_notation) / syntax such as uint8a_varname it can be recompiled / transpiled to C++ (and also OpenCL and I presume OpenGL) relatively easily.

**Comment by mateogianolio** [comment]
Yes, I also had a look at that code and there was no straightforward way to integrate it with this project. I was also thrown off by the unconventional coding style, hehe. That’s the reason I started drafting the NDArray class in #132.

My inspiration for ndarray (attribute and method-wise) is of course numpy, do you have any examples of differing implementations?

**Comment by metabench** [comment]
I'm not very experienced with current vector / matrix / tensor frameworks. Basically I want the API to be as simple as possible, to have a core that is fairly simple conceptually, and as performant as possible.

If my initial thoughts right now are significantly different to numpy and how you want Vectorious to be, then I'll see how well my rival Tensor implementation works. If it turns out to have the right interface for Vectorious, then it could immediately be of use.

Here are my most recent comments / thoughts on my tensor class and theory about indexes. It would help if you would let me know if this makes any sense to you, is wrong, obvious and very basic, or whatever. To me at least, I feel as though I have made a personal breakthrough this evening thinking about how tensors are to be indexed.

`

// Shape
//  Itself a TA
//  Likely UInt32Array

// Rank - number of dimensions

// Maybe worth making Position data type.

// Tensor type

// let t = new Tensor(shape), v;

// t.set_i(idx, value);
// v = t.get_i(idx);

// t.set(ta_pos, value);
// v = t.get(ta_pos);

// --- Maybe:
// t.set_t(ta_pos, tensor) - writes the tensor to that position.
// t.get_t(ta_pos, shape) - gets that position.

// t.slice(pos, shape)

// Animations and frames would be a good way to think through and test a few tensors.
//  Relatively low order, but an image could be a 3d tensor: x, y, pixel_component.

// Then this would be nice to convert to C++ and other optimization methods such as WASM.

// Tensor can't change shape

class Tensor {
    constructor(ta_shape) {
        // Do more within the constructor s optimization, using local variables rather than this?


        // index to coordinates
        // coordinates to index
        // movement vectors to index changes

        // y * w + x formula extension.

        // p2 * d1 + p1;



        // 3d x, y, z:

        // z dimension being layers going upwards
        // (w * h * z) + (w * y) + (x)


        //        lower dimension sizes multiplied together.
        //       (d1 * d2 * p3) + (d2 * p2) + p1
        //             z             y        x
        // d:          3             2        1
        // lowerds:    2, 1          1 


        // Then t could be the next dimension / number of frames into the 3d-space animation
        //
        // (width * height * depth * t) + (width * height * z) + (width * y) + x
        // (d1 * d2 * d3 * p4) + (d1 * d2 * p3) + (d1 * p2) + p1
        //       t                     z             y        x


         








        // r1*p1*r2*p2*


        // then index function uses that same shape.



    }

}
`

**Comment by metabench** [comment]
https://github.com/metabench/ta-tensor/blob/master/ta-tensor.js

@mateogianolio ta-tensor would definitely benefit from your help. I've made a basic version. It should be quite fast, but it's just a first working version. The most critical functions, in my opinion, are conversions between coordinates and indexes. Doing so takes a few multiplications and divisions.

I've decided to make it similar to TensorFlow in terms of API where appropriate and possible.

The thing which I am considering now is how to set a smaller tensor within a larger one. Iterating through corresponding coordinates and index values looks like the way.

I'm using image processing tasks / animation construction as a means to develop tensors of moderate complexity that will be easiest to test, as well as come up with useful and high-performance code to do those things.

Later on down the line it would be nice to use the tensor to represent multi-layer perceptrons and other tools for AI, but right now I want to test it and give it functionality suitable for image processing.

Also, it's occurred to me that storing every value in a Uint8Array when combined with some aspects of tensor theory could mean that in practise more complex data structures could be accessed, because they can be represented as a part of a large Uint8Array with abstractions over them. Optimization would likely present other concerns.
