### ISSUE TITLE
GPU and future performance

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#68]
> Discussion regarding the addition of GPU support and/or other performance-enhancing efforts to **Vectorious**.

**Related links**
- [nLAPACK](https://github.com/mateogianolio/nlapack)
- [weblas](https://github.com/waylonflinn/weblas) by @waylonflinn 
- https://github.com/codeforscience/webdata/issues/8
- [WebAssembly](https://github.com/webassembly)
- [opencljs-experiments](https://github.com/metabench/opencljs-experiments) by @metabench 
- [cl.js](https://github.com/graphistry/cljs)
- [clMAGMA](http://icl.cs.utk.edu/magma/software/index.html)

**Comment by metabench** [comment]
Do you have a specific GPU technology in mind? I did a bit of previous work using OpenCL - https://github.com/metabench/opencljs-experiments. I got fast results carrying out a small number of simple operations on a fairly large (as in hundreds / low thousands of MB) sets of data. To get started with OpenCL it was a really steep learning curve. Quite a lot of boilerplate is required to carry out some relatively simple things. My experiments partly involved generating this boilerplate from a greatly reduced subset of JavaScript. My concern about introducing an abstraction that reduces boilerplate is that it's another source of complexity, and risk that it's a leaky abstraction. To be honest I was greatly impressed with my KernelScript code but I have not been hyping up the idea at all. Such a tool may be worth using to generate lots of repetitive boilerplate OpenCL code (whether at run-time or during the programming stage).

What would you think about having me integrate OpenCL into a small number of operations such as basic arithmetic within a new branch?

Also, are SIMD operations currently being used to speed up processing where appropriate? The high performance algebra libraries that vectorious references use SIMD. Are there places within vectorius that do not use SIMD but it would be appropriate?

The Intel compiler makes some optimizations regarding SIMD. It could increase performance. Unfortunately some evidence shows that it has sub-optimal performance on some very capable non-Intel (AMD) processors, so this stands against its use in general purpose high performance applications. It would be an interesting result at least to see what effect the use of the Intel C++ compiler has on the speed.

**Comment by mateogianolio** [comment]
GPU is kind of unexplored territory for me so I'm open for any suggestions. Go ahead and open a new branch!

**Comment by lucidrains** [comment]
please deliver.. lol

**Comment by mateogianolio** [comment]
Interesting: https://github.com/graphistry/cljs

**Comment by mateogianolio** [comment]
Also interesting:

> The MAGMA project aims to develop a dense linear algebra library similar to LAPACK but for heterogeneous/hybrid architectures, starting with current "Multicore+GPU" systems.

http://icl.cs.utk.edu/magma/software/index.html
PDF: http://www.netlib.org/lapack/lawnspdf/lawn275.pdf

**Comment by mateogianolio** [comment]
I've done some initial benchmarking comparing BLAS saxpy with my own CL.js version of saxpy. 

https://gist.github.com/mateogianolio/00ce0da60f9b9304ec17

Vectors are of length 1048576. Output on my MacBook Pro (Intel Iris Graphics 6100 1536 MB):

```
saxpy (OpenCL) x 5,401 ops/sec ±2.70% (76 runs sampled)
saxpy (CBLAS) x 1,500 ops/sec ±0.60% (89 runs sampled)
```

**Comment by mateogianolio** [comment]
I'm thinking of writing bindings similar to nBLAS for OpenCL (clBLAS) and CUDA (cuBLAS).

**Comment by metabench** [comment]
@mateogianolio I'm doing some more work on high-performance numeric programming. I'd like to use and contribute to vectorious more, but there is one issue which prevents me from using vectorious for a whole variety of purposes.

That issue is the requirement to have BLAS preinstalled on the system. The major problem for me is not my own installation of it, but the fact that those who download derivative libraries would have to install BLAS themselves. This makes automated installation and deployment a lot more difficult. While you and other developers may have strong ideas in the other direction, I hope you can at least understand that ease of deployment is important.

The kinds of tools which would benefit from vectorious's capabilities while being easy to install would be a JPEG encoder/decoder, which could then be used within a web server library. The end user should not have to install BLAS in that kind of situation.

Is this something that you may change your mind about?

If not, would you be interested in supporting a vectorious-easy-install fork?

**Comment by mateogianolio** [comment]
@metabench Great to hear from you! I agree that ease of deployment is crucial for adoption and I will look for ways to include BLAS either in the installation of this library or in the installation of nBLAS. There are some issues that need to be addressed though.

* Which BLAS is the best (or easiest to setup) for each operating system?
* How would we detect if the user has already installed BLAS?
* How would we write a script to install BLAS that works on all platforms that have support for it?

Meanwhile, I'm interested in supporting a vectorious-easy-install fork where we can address some of these issues and when we feel confident enough it works we might be able to include them here.

**Comment by metabench** [comment]
@mateogianolio Hello and thanks for the welcome.

Performance-wise, I recommend linking C++ code within the library itself rather than having another function call to a referenced module. That would be worth testing rather than taking my word for it, but it's just one potential way I think the code could be slowed down.

Having seen the nBLAS project, if it does what it does well, I'd suggest making a different project that does something different. Maybe node-blas, node-native-blas. Maybe you could rename nBLAS if in the longer run you decide that compiling BLAS rather than referencing it is more in line with your needs.

In terms of easiness of installation, compiling BLAS code through NPM compilation would be best. The C++ source code gets delivered and compiled by NPM. Right now I'm not sure about details of controlling 32 or 64 bit compilation, I think my code automatically compiled as 64 bit because that's what version of node I was using.

Both node and the Chromium Browser projects use V8, and include V8 source code within their distributions. I recommend taking that approach for vectorious in the longer run but also think making a version of it that operates that way as a fork would work well so the projects can be compared side-by-side. It would take ongoing work to keep the vectorious (or its easy-instyall version) up-to-date. Undiscovered security bugs like buffer overruns in BLAS if they were ever to be discovered would be a part of the vectorious code distribution too unless they were patched.

- Which BLAS is the best (or easiest to setup) for each operating system?

I don't know which version of BLAS is best, or how the versions are different from each other, or how much work it would be to change to a different BLAS library. Having looked at nBLAS, which uses CBLAS, I saw this location to download CBLAS source code:

http://www.netlib.org/blas/#_cblas

Is that the right place to get code which will compile for use with vectorious (on Windows) or would you recommend somewhere else? NPM and C++ compilation generally works well cross-platform, without needing to do anything to support particular platforms. Quite how things work regarding compiling for CPUs with different features would work is another question too, but I think that can all be handled by directives within the code.

I'd also be keen (if it will get the software up and running soon) is to give it high minimum system requirements, such as a Haswell CPU. vectorious-(easy-install/native)-haswell could be one project that gets made, and provides best performance for newer Intel processors. The structure of the project may be a useful basis for a more versatile system using directives. I'd be interested in writing a version customised for the upcoming AMD Zen feature set too.

It's worth thinking in terms of:

- Lowest common denominator builds
- Targeted builds
- Versatile builds

I am most interested in writing a targeted build soon.

When I worked on Vectorious a while ago my thoughts on its eventual optimization were to write highly optimized JavaScript, then port that to C/C++, then write SIMD optimizations. It may be that taking pre-existing BL:AS code and using it within vectorious is a route towards that same eventual result, but without having to develop BLAS code. 

I have written some SIMD code already using Haswell features and compiles it through NPM on Windows 8. I would be interested in writing code for vectorious in C/C++, I'm not sure if code I write that does that would count as BLAS (fitting the acronym) or if BLAS is a particular feature set and API which I would just be writing some similar code.

- How would we detect if the user has already installed BLAS?

Detecting it would be an advantage. Version comparisons and benchmarks during installation to choose may be better. Giving the developer ultimate control (should they choose to use it) over which BLAS library to use sounds best. In the long run I'm not convinced that referencing a BLAS library is the right approach anyway, but benchmarking comparisons other forks would put this to the test.

- How would we write a script to install BLAS that works on all platforms that have support for it?

It could be done, I think. That's not the approach I want to take in the near future but I'll get onto that. There are points within the NPM installation process where other code can be executed. Other compilers could be invoked. I'm not so sure that's the right approach overall. It raises the possibility of using a paid-for compiler, such as from Intel.

I wish to use npm distribute and install all needed code.

**Comment by mateogianolio** [comment]
It seems like it is now possible to install GPU BLAS that will transparently replace or reroute the standard CPU CBLAS routines (see https://github.com/CNugteren/CLBlast#using-the-library and http://docs.nvidia.com/cuda/nvblas/index.html#axzz4IfVfPuKV). Maybe we could find a way to incorporate this as a first step.

**Comment by metabench** [comment]
@mateogianolio Now that 5.0.0 is on it's way, any thoughts about how and where it would be best to integrate GPU acceleration? Now that the API soon allows for tensors, it looks like a somewhat different task. I'm quite interested in tensors for a variety of purposes.

Maybe I will make a rival or Vectorious branch that has got a (much?) smaller feature set, but implements those features using a different codebase structure that's made to carry out some of the speedup / compilation improvements that have been discussed already.

If this shows success with benchmarks, I'd next look at porting more current Vectorious functionality over to some new ways of doing things.

**Comment by mateogianolio** [comment]
https://github.com/turbo/js

**Comment by mateogianolio** [comment]
Moved to discussions.
