### ISSUE TITLE
Website for vectorious

### ISSUE THREAD

**Issue by omaressa** [mateogianolio/vectorious#72]
Hi, I've been using vectorious lately and i love it! Thanks for amazing work..Is there a website (github page or on its own domain) for vectorious?

**Comment by mateogianolio** [comment]
Hi! Thanks and I'm glad you enjoy it! It used to have a website with docs, but not since I moved that to the wiki.

It would be great to have a site where people could try it out, but it hasn't exactly been my top priority.

**Comment by omaressa** [comment]
Hi @mateogianolio , I'd love to design one for this amazing project - I'll start work on it in a day or so..anything particular that you want included on the pages?Should i submit the site content to the main branch?

**Comment by mateogianolio** [comment]
That is awesome! Fork this repo, create a `gh-pages` branch with `git checkout -b gh-pages`, commit your changes there and then submit a pull request when you feel it's ready.

About the content; anything that makes it easier for people to use it or that makes it more fun, either by showing examples or presenting real-world applications (e.g. just mentioning neural networks gets people excited). Since there isn't already a website you are pretty much free to do whatever you want. I'm looking forward to seeing what you can come up with!

**Comment by omaressa** [comment]
@mateogianolio  Thank you, I've submitted the pull request with website files - Hope you like it :) Let me know if any changes are required :). Thank you so much for creating this awesome library!

**Comment by mateogianolio** [comment]
Solved with auto-generated documentation for now (#107).
